## 1. Execute full pipeline

In [1]:
import random
import time

from keras_tuner import RandomSearch

import numpy as np

import pandas as pd

import tensorflow as tf

from config.constants import (
    FORECAST_HORIZON, NB_TRIALS,
    OBSERVATION_WINDOW, SEED, TRAIN_PERC
)

from src.cpd import CPDCostFunction, CPDMethod, CPDDetectorFactory
from src.data_reader import fill_na, read_dataset, split_X_y, split_train_test
from src.forecaster import InternalForecaster, ForecasterType, LSTMForecasterHyperModel
from src.scaler import ScalerFactory, ScalerType
from src.utils import get_error_results

tf.get_logger().setLevel('ERROR')

np.random.seed(SEED)
random.seed(SEED)
tf.random.set_seed(SEED)

/Users/zamith/Doutorado/OptimizingForecastingCPD/.venv/lib/python3.12/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):

In [2]:
print("Available devices:", tf.config.list_physical_devices())
print("Is GPU available?", tf.config.list_physical_devices('GPU'))

Available devices: [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
Is GPU available? []

In [3]:
if tf.config.list_physical_devices("GPU"):
    try:
        tf.config.set_visible_devices([], "GPU")  # Hide traditional GPUs if any (like external ones)
        tf.config.experimental.set_memory_growth(tf.config.list_physical_devices("GPU")[0], True)
        print("✅ TensorFlow is using Apple GPU via MPS")
    except Exception as e:
        print("⚠️ Error setting MPS GPU:", e)
else:
    print("❌ No GPU found, running on CPU")

❌ No GPU found, running on CPU

In [4]:
timestamp = 'validate_pipeline'
dataset_domain_argv = 'UCI'
dataset_argv = 'AIR_QUALITY'
cpd_method_argv = 'Window'
cpd_cost_function_argv = 'L1'
forecaster_type_argv = 'LSTM'

In [5]:
execution_id = f"{timestamp}_{dataset_domain_argv}_{dataset_argv}_{cpd_method_argv}_{cpd_cost_function_argv}_{forecaster_type_argv}_{SEED}"
cpd_method = CPDMethod.from_str(cpd_method_argv)
cpd_cost_function = CPDCostFunction.from_str(cpd_cost_function_argv)
change_point_approach = f"{cpd_method.value.title()} {cpd_cost_function.value.title()}"
forecaster_type = ForecasterType.from_str(forecaster_type_argv)

In [6]:
print(f"[Step 1] Reading dataset {dataset_argv} from {dataset_domain_argv}")
df, variables = read_dataset(dataset_domain_argv, dataset_argv)
print(f"Variables: {variables}")

[Step 1] Reading dataset AIR_QUALITY from UCI
Variables: ['CO(GT)', 'C6H6(GT)', 'NOx(GT)', 'NO2(GT)', 'T', 'RH']

In [7]:
print("[Step 2] Splitting data into train_val and test and filling missing values")
train_val, test = split_train_test(df)
train_val = fill_na(train_val, variables, limit_direction="forward")
test = fill_na(test, variables, limit_direction="both")

[Step 2] Splitting data into train_val and test and filling missing values

In [8]:
report = {
    'execution_id': execution_id,
    'timestamp': timestamp,
    'cpd_method': cpd_method.value,
    'cpd_cost_function': cpd_cost_function.value,
    'change_point_approach': change_point_approach,
    'forecaster_type': forecaster_type.value,
    'seed': SEED,
    'observation_window': OBSERVATION_WINDOW,
    'train_perc': TRAIN_PERC,
    'nb_trials': NB_TRIALS,
    'dataset_domain': dataset_domain_argv,
    'dataset': dataset_argv,
    'variables': variables,
    'dataset_shape': df.shape,
    'train_val_shape': train_val.shape,
    'test_shape': test.shape,
}

In [9]:
print(f"[Step 3] Detecting cut point ({change_point_approach})")
start_time = time.time()
change_point_detector = CPDDetectorFactory.create_detector(cpd_method, cpd_cost_function)
change_point, change_point_perc = change_point_detector.find_change_point(train_val, variables)
end_time = time.time()
detect_change_point_duration = end_time - start_time
print(f"Change point: {change_point}, Change point percentage: {change_point_perc}")
report.update({
    'detect_change_point_duration': detect_change_point_duration,
    'change_point': str(change_point),
    'change_point_perc': change_point_perc
})

[Step 3] Detecting cut point (Window L1)
Change point: 5385, Change point percentage: 71.9438877755511

In [10]:
print("[Step 4] Reducing train_val based on change point")
start_time = time.time()
reduced_train_val = change_point_detector.apply_change_point(train_val, change_point)
end_time = time.time()
apply_change_point_duration = end_time - start_time
report.update({
    'apply_change_point_duration': apply_change_point_duration,
    'reduced_train_val.shape': reduced_train_val.shape,
})

[Step 4] Reducing train_val based on change point

In [11]:
print("[Step 5] Splitting train_val into train and val")
reduced_train, reduced_val = split_train_test(reduced_train_val)
report.update({
    'reduced_train.shape': reduced_train.shape,
    'reduced_val.shape': reduced_val.shape,
})

[Step 5] Splitting train_val into train and val

In [12]:
print("[Step 6] Fitting scaler on train and applying on train and val")
start_time = time.time()
scaler = ScalerFactory.create_scaler(ScalerType.STANDARD, variables)
scaled_reduced_train = scaler.fit_scale(reduced_train)
scaled_reduced_val = scaler.scale(reduced_val)
end_time = time.time()
fit_apply_scaler_train_val_duration = end_time - start_time
report.update({
    'fit_apply_scaler_train_val_duration': fit_apply_scaler_train_val_duration,
})

[Step 6] Fitting scaler on train and applying on train and val

In [13]:
print("[Step 7] Splitting train and val into X and y")
X_reduced_scaled_train, y_reduced_scaled_train = split_X_y(scaled_reduced_train)
X_reduced_scaled_val, y_reduced_scaled_val = split_X_y(scaled_reduced_val)
report.update({
    'X_reduced_scaled_train.shape': X_reduced_scaled_train.shape,
    'y_reduced_scaled_train.shape': y_reduced_scaled_train.shape,
    'X_reduced_scaled_val.shape': X_reduced_scaled_val.shape,
    'y_reduced_scaled_val.shape': y_reduced_scaled_val.shape,
})

[Step 7] Splitting train and val into X and y

In [14]:
y_reduced_scaled_train[0]

array([[ 0.2794384 ,  0.94363348, -0.22221197, -0.31901199,  2.57306525,
        -0.60601449],
       [ 0.93656296,  1.80147318,  0.20238044,  0.04013744,  2.3587538 ,
        -0.29619734],
       [ 1.81272904,  2.47234781,  0.6914199 ,  0.08239032,  2.20289093,
        -0.06383447],
       [ 1.26512524,  1.66949784,  0.35022958, -0.19225337,  2.12495949,
        -0.10901614],
       [ 0.88180258,  1.38355127,  0.17205241, -0.25563268,  1.91064804,
         0.1168922 ],
       [ 0.88180258,  1.30656566,  0.25924549, -0.53027636,  1.67685373,
         0.43316387],
       [ 0.8270422 ,  1.08660677,  0.17963441, -0.53027636,  1.52099086,
         0.56870888]])

In [15]:
y_reduced_scaled_train[1]

array([[ 0.93656296,  1.80147318,  0.20238044,  0.04013744,  2.3587538 ,
        -0.29619734],
       [ 1.81272904,  2.47234781,  0.6914199 ,  0.08239032,  2.20289093,
        -0.06383447],
       [ 1.26512524,  1.66949784,  0.35022958, -0.19225337,  2.12495949,
        -0.10901614],
       [ 0.88180258,  1.38355127,  0.17205241, -0.25563268,  1.91064804,
         0.1168922 ],
       [ 0.88180258,  1.30656566,  0.25924549, -0.53027636,  1.67685373,
         0.43316387],
       [ 0.8270422 ,  1.08660677,  0.17963441, -0.53027636,  1.52099086,
         0.56870888],
       [-0.26816541,  0.09679173, -0.64680438, -0.88942579,  1.46254228,
         0.52352721]])

In [16]:
y_reduced_scaled_train[2]

array([[ 1.81272904,  2.47234781,  0.6914199 ,  0.08239032,  2.20289093,
        -0.06383447],
       [ 1.26512524,  1.66949784,  0.35022958, -0.19225337,  2.12495949,
        -0.10901614],
       [ 0.88180258,  1.38355127,  0.17205241, -0.25563268,  1.91064804,
         0.1168922 ],
       [ 0.88180258,  1.30656566,  0.25924549, -0.53027636,  1.67685373,
         0.43316387],
       [ 0.8270422 ,  1.08660677,  0.17963441, -0.53027636,  1.52099086,
         0.56870888],
       [-0.26816541,  0.09679173, -0.64680438, -0.88942579,  1.46254228,
         0.52352721],
       [-0.76100883, -0.48609934, -1.01453173, -1.1218166 ,  1.44305942,
         0.52998174]])

In [17]:
print("[Step 8] Running HPO and NAS")
n_variables = len(variables)
forecaster_hypermodel = LSTMForecasterHyperModel(
    n_variables=n_variables
)
forecaster_tuner = RandomSearch(
    forecaster_hypermodel,
    objective='val_loss',
    max_trials=3,
    executions_per_trial=1,
    directory=f"outputs/tuner/delete_me",
    project_name="delete_me",
    seed=SEED,
    overwrite=True,
    distribution_strategy=tf.distribute.MirroredStrategy()
)
start_time = time.time()
forecaster_tuner.search(
    X_reduced_scaled_train,
    y_reduced_scaled_train,
    validation_data=(X_reduced_scaled_val, y_reduced_scaled_val),
    shuffle=False,
)
end_time = time.time()
tuner_duration = end_time - start_time
report.update({
    'tuner_duration': tuner_duration
})

Trial 3 Complete [00h 00m 04s]
val_loss: 0.34673964585128586

Best val_loss So Far: 0.34673964585128586
Total elapsed time: 00h 00m 39s

In [18]:
print("[Step 9] Retrieving best model")
best_trial = forecaster_tuner.oracle.get_best_trials(num_trials=1)[0]
best_forecaster_model = forecaster_tuner.get_best_models(num_models=1)[0]
print(f"Trial ID: {best_trial.trial_id}")
print(f"Hyperparameters: {best_trial.hyperparameters.values}")
print(f"Score: {best_trial.score}")
print("-" * 40)
best_forecaster_model.summary()
best_forecaster_model = InternalForecaster(
    best_forecaster_model,
    len(variables),
    best_trial.hyperparameters.values['batch_size'],
    best_trial.hyperparameters.values['epochs'],
)
report.update({
    'best_trial_id': best_trial.trial_id,
    'best_trial_hyperparameters': best_trial.hyperparameters.values,
    'best_trial_score': best_trial.score,
    'best_forecaster_model': best_forecaster_model.summary(),
})

[Step 9] Retrieving best model
Trial ID: 2
Hyperparameters: {'num_layers': 1, 'dropout_rate': 0.2, 'recurrent_dropout_rate': 0.1, 'l2_reg': 0.0001, 'use_batch_norm': True, 'learning_rate': 0.005, 'units_0': 32, 'units_1': 32, 'units_2': 64, 'units_3': 96, 'batch_size': 96, 'epochs': 125}
Score: 0.34673964585128586
----------------------------------------

/Users/zamith/Doutorado/OptimizingForecastingCPD/.venv/lib/python3.12/site-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 16 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 32)             │         4,992 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 32)             │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 42)             │         1,386 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ reshape (Reshape)               │ (None, 7, 6)           │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 6,506 (25.41 KB)

 Trainable params: 6,442 (25.16 KB)

 Non-trainable params: 64 (256.00 B)

In [19]:
print("[Step 10] Fitting scaler on train_val and applying on train_val and test")
start_time = time.time()
scaler = ScalerFactory.create_scaler(ScalerType.STANDARD, variables)
scaled_reduced_train_val = scaler.fit_scale(reduced_train_val)
scaled_test = scaler.scale(test)
end_time = time.time()
fit_apply_scaler_train_val_test_duration = end_time - start_time
report.update({
    'fit_apply_scaler_train_val_test_duration': fit_apply_scaler_train_val_test_duration,
})

[Step 10] Fitting scaler on train_val and applying on train_val and test

In [20]:
print("[Step 11] Splitting train_val and test into X and y")
X_reduced_scaled_train_val, y_reduced_scaled_train_val = split_X_y(scaled_reduced_train_val)
X_scaled_test, y_scaled_test = split_X_y(scaled_test)
report.update({
    'X_reduced_scaled_train_val.shape': X_reduced_scaled_train_val.shape,
    'y_reduced_scaled_train_val.shape': y_reduced_scaled_train_val.shape,
    'X_scaled_test.shape': X_scaled_test.shape,
    'y_scaled_test.shape': y_scaled_test.shape,
})

[Step 11] Splitting train_val and test into X and y

In [21]:
print("[Step 12] Retraining best model")
start_time = time.time()
best_forecaster_model.fit(
    X_reduced_scaled_train_val,
    y_reduced_scaled_train_val,
    shuffle=False
)
end_time = time.time()
retrain_duration = end_time - start_time
report.update({
    'retrain_duration': retrain_duration,
})

[Step 12] Retraining best model
Epoch 1/125
21/21 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.6522
Epoch 2/125
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6440
Epoch 3/125
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6433
Epoch 4/125
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6265
Epoch 5/125
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6166
Epoch 6/125
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6284
Epoch 7/125
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6122
Epoch 8/125
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6181
Epoch 9/125
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6046
Epoch 10/125
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6039
Epoch 11/125
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6143
Epoch 12/125
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.6046
Epoch 13/125
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6093
Epoch 14/125
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5808
Epoch 15/125
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5803
Epoch 16/125
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5966
Epoch 17/125
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6092
Epoch 18/125
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5986
Epoch 19/125
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5864
Epoch 20/125
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.5782
Epoch 21/125
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5849
Epoch 22/125
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5743
Epoch 23/125
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5876
Epoch 24/125
21/21 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.6012

In [22]:
print("[Step 13] Forecasting for test")
start_time = time.time()
y_scaled_pred = best_forecaster_model.forecast(X_scaled_test)
y_scaled_test_flat = y_scaled_test.reshape(-1, n_variables)
y_scaled_pred_flat = y_scaled_pred.reshape(-1, n_variables)
end_time = time.time()
forecasting_test_duration = end_time - start_time
report.update({
    'forecasting_test_duration': forecasting_test_duration,
})

[Step 13] Forecasting for test
58/58 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

2025-12-27 15:14:20.650546: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
	 [[{{node MultiDeviceIteratorGetNextFromShard}}]]

In [23]:
y_scaled_test_flat

array([[-1.23055822, -1.25086781, -1.16213415, -0.87719569, -2.06214374,
        -0.13780333],
       [-1.11462147, -1.18137868, -1.05524888, -0.6343508 , -1.94346707,
        -0.31248902],
       [-0.94071634, -0.99607432, -1.01566174, -0.52396676, -1.86434929,
        -0.3528011 ],
       ...,
       [-0.12915906,  0.06942571, -0.37435011,  1.24217789,  2.74426146,
        -2.84543152],
       [-0.3030642 , -0.26643843, -0.60395551,  0.82271854,  3.0211737 ,
        -3.16792817],
       [-0.24509582,  0.0115181 , -0.4851941 ,  1.08764024,  3.06073259,
        -3.1948029 ]], shape=(12964, 6))

In [24]:
y_scaled_pred_flat

array([[-1.1930964 , -1.1355519 , -1.1188724 , -1.1372075 , -1.3058625 ,
        -0.33406618],
       [-0.9886556 , -0.8436998 , -0.80726504, -0.9049927 , -1.280415  ,
        -0.3049629 ],
       [-0.8419529 , -0.59216356, -0.6446651 , -0.7028308 , -1.1771121 ,
        -0.41542137],
       ...,
       [ 0.27315068,  0.27712303,  0.37222263,  0.68851835,  0.52475125,
        -0.6963279 ],
       [ 0.29258713,  0.36233482,  0.28528455,  0.4942365 ,  0.59878325,
        -0.68601996],
       [ 0.49885935,  0.5175561 ,  0.4714848 ,  0.6540893 ,  0.60640067,
        -0.5814777 ]], shape=(12964, 6), dtype=float32)

In [25]:
print("[Step 14] Descaling data")
start_time = time.time()
y_test = scaler.descale(pd.DataFrame(y_scaled_test_flat, columns=variables))
y_pred = scaler.descale(pd.DataFrame(y_scaled_pred_flat, columns=variables))
end_time = time.time()
descaling_duration = end_time - start_time
report.update({
    'descaling_duration': descaling_duration,
})

[Step 14] Descaling data

In [26]:
y_test

       CO(GT)  C6H6(GT)  NOx(GT)  NO2(GT)     T    RH
0         0.5       1.0     94.0     79.0   2.6  58.6
1         0.7       1.6    121.0     90.0   3.2  56.0
2         1.0       3.2    131.0     95.0   3.6  55.4
3         3.0      15.9    552.0    169.0   1.8  63.3
4         4.1      18.0    614.0    199.0   2.4  60.2
...       ...       ...      ...      ...   ...   ...
12959     3.1      13.5    472.0    190.0  21.9  29.3
12960     2.4      11.4    353.0    179.0  24.3  23.7
12961     2.4      12.4    293.0    175.0  26.9  18.3
12962     2.1       9.5    235.0    156.0  28.3  13.5
12963     2.2      11.9    265.0    168.0  28.5  13.1

[12964 rows x 6 columns]

In [27]:
y_pred

         CO(GT)   C6H6(GT)     NOx(GT)     NO2(GT)          T         RH
0      0.564625   1.995688  104.928223   67.222397   6.423571  55.678848
1      0.917301   4.515669  183.642532   77.740898   6.552227  56.112019
2      1.170375   6.687545  224.716446   86.898102   7.074501  54.467968
3      1.401674   7.278079  281.814972   99.713173   7.981664  52.776577
4      1.743579   8.806679  318.559906  104.528358   8.870239  50.748219
...         ...        ...         ...         ...        ...        ...
12959  4.041748  18.439140  678.263550  170.514420  14.192598  54.821400
12960  3.528124  15.820251  578.466431  159.305389  15.046953  52.307022
12961  3.094016  14.193351  481.589722  149.921219  15.678703  50.286987
12962  3.127545  14.929107  459.628540  141.120941  16.052990  50.440411
12963  3.483381  16.269356  506.664062  148.361694  16.091503  51.996407

[12964 rows x 6 columns]

In [28]:
print("[Step 15] Calculating evaluation metrics")
total_duration = sum(value for key, value in report.items() if key.endswith('_duration'))
error_results = get_error_results(y_test, y_pred, variables)
print(f"Obtained error results: {error_results}")
report.update({
    'total_duration': total_duration,
    'error_results': error_results,
})

[Step 15] Calculating evaluation metrics
Obtained error results: {'Avg_MAPE': 3166110645413.328, 'Avg_MAE': 31.691169073740266, 'Avg_MSE': 5944.485804325924, 'Avg_RMSE': 42.41185396831123, 'Avg_R2': 0.31991323189217086, 'Avg_WAPE': np.float64(0.3702461971109843), 'CO(GT)_MAPE': 0.9879251936579617, 'CO(GT)_MAE': 0.9043160629005397, 'CO(GT)_MSE': 1.4915963293758976, 'CO(GT)_RMSE': 1.2213092685212446, 'CO(GT)_R2': 0.22301188358341117, 'CO(GT)_WAPE': np.float64(0.47634549932826376), 'C6H6(GT)_MAPE': 1.2717804252874847, 'C6H6(GT)_MAE': 4.298014400954545, 'C6H6(GT)_MSE': 31.720384775559218, 'C6H6(GT)_RMSE': 5.632085295479749, 'C6H6(GT)_R2': 0.24184178633372533, 'C6H6(GT)_WAPE': np.float64(0.5371826529770661), 'NOx(GT)_MAPE': 0.682037266403898, 'NOx(GT)_MAE': 134.37906568339488, 'NOx(GT)_MSE': 32923.81080545644, 'NOx(GT)_RMSE': 181.44919621055487, 'NOx(GT)_R2': 0.24831197335347188, 'NOx(GT)_WAPE': np.float64(0.44614264288682143), 'NO2(GT)_MAPE': 0.284132051367026, 'NO2(GT)_MAE': 38.364741155005866, 'NO2(GT)_MSE': 2554.4333219850464, 'NO2(GT)_RMSE': 50.541402057966756, 'NO2(GT)_R2': 0.12668833052399076, 'NO2(GT)_WAPE': np.float64(0.268838938328075), 'T_MAPE': 18996663872476.484, 'T_MAE': 2.980624073575222, 'T_MSE': 13.911031305850498, 'T_RMSE': 3.729749496393893, 'T_R2': 0.5991462013961304, 'T_WAPE': np.float64(0.29763446024713913), 'RH_MAPE': 0.2572511644517666, 'RH_MAE': 9.220253066610532, 'RH_MSE': 141.54768610327235, 'RH_RMSE': 11.897381480950855, 'RH_R2': 0.4804792161622957, 'RH_WAPE': np.float64(0.18533936387059935)}

In [29]:
report

{'execution_id': 'validate_pipeline_UCI_AIR_QUALITY_Window_L1_LSTM_1001',
 'timestamp': 'validate_pipeline',
 'cpd_method': 'Window',
 'cpd_cost_function': 'L1',
 'change_point_approach': 'Window L1',
 'forecaster_type': 'LSTM',
 'seed': 1001,
 'observation_window': 14,
 'train_perc': 0.8,
 'nb_trials': 30,
 'dataset_domain': 'UCI',
 'dataset': 'AIR_QUALITY',
 'variables': ['CO(GT)', 'C6H6(GT)', 'NOx(GT)', 'NO2(GT)', 'T', 'RH'],
 'dataset_shape': (9357, 7),
 'train_val_shape': (7485, 7),
 'test_shape': (1872, 7),
 'detect_change_point_duration': 0.06582999229431152,
 'change_point': '5385',
 'change_point_perc': np.float64(71.9438877755511),
 'apply_change_point_duration': 9.012222290039062e-05,
 'reduced_train_val.shape': (2100, 7),
 'reduced_train.shape': (1680, 7),
 'reduced_val.shape': (420, 7),
 'fit_apply_scaler_train_val_duration': 0.006189823150634766,
 'X_reduced_scaled_train.shape': (1660, 14, 6),
 'y_reduced_scaled_train.shape': (1660, 7, 6),
 'X_reduced_scaled_val.shape': (400, 14, 6),
 'y_reduced_scaled_val.shape': (400, 7, 6),
 'tuner_duration': 38.61628699302673,
 'best_trial_id': '2',
 'best_trial_hyperparameters': {'num_layers': 1,
  'dropout_rate': 0.2,
  'recurrent_dropout_rate': 0.1,
  'l2_reg': 0.0001,
  'use_batch_norm': True,
  'learning_rate': 0.005,
  'units_0': 32,
  'units_1': 32,
  'units_2': 64,
  'units_3': 96,
  'batch_size': 96,
  'epochs': 125},
 'best_trial_score': np.float64(0.34673964585128586),
 'best_forecaster_model': 'Model: "sequential"\n┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓\n┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃\n┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩\n│ lstm (LSTM)                     │ (None, 32)             │         4,992 │\n├─────────────────────────────────┼────────────────────────┼───────────────┤\n│ batch_normalization             │ (None, 32)             │           128 │\n│ (BatchNormalization)            │                        │               │\n├─────────────────────────────────┼────────────────────────┼───────────────┤\n│ dense (Dense)                   │ (None, 42)             │         1,386 │\n├─────────────────────────────────┼────────────────────────┼───────────────┤\n│ reshape (Reshape)               │ (None, 7, 6)           │             0 │\n└─────────────────────────────────┴────────────────────────┴───────────────┘\n Total params: 6,506 (25.41 KB)\n Trainable params: 6,442 (25.16 KB)\n Non-trainable params: 64 (256.00 B)\n\n',
 'fit_apply_scaler_train_val_test_duration': 0.003728151321411133,
 'X_reduced_scaled_train_val.shape': (2080, 14, 6),
 'y_reduced_scaled_train_val.shape': (2080, 7, 6),
 'X_scaled_test.shape': (1852, 14, 6),
 'y_scaled_test.shape': (1852, 7, 6),
 'retrain_duration': 2.9432339668273926,
 'forecasting_test_duration': 0.4603750705718994,
 'descaling_duration': 0.00566411018371582,
 'total_duration': 42.101398229599,
 'error_results': {'Avg_MAPE': 3166110645413.328,
  'Avg_MAE': 31.691169073740266,
  'Avg_MSE': 5944.485804325924,
  'Avg_RMSE': 42.41185396831123,
  'Avg_R2': 0.31991323189217086,
  'Avg_WAPE': np.float64(0.3702461971109843),
  'CO(GT)_MAPE': 0.9879251936579617,
  'CO(GT)_MAE': 0.9043160629005397,
  'CO(GT)_MSE': 1.4915963293758976,
  'CO(GT)_RMSE': 1.2213092685212446,
  'CO(GT)_R2': 0.22301188358341117,
  'CO(GT)_WAPE': np.float64(0.47634549932826376),
  'C6H6(GT)_MAPE': 1.2717804252874847,
  'C6H6(GT)_MAE': 4.298014400954545,
  'C6H6(GT)_MSE': 31.720384775559218,
  'C6H6(GT)_RMSE': 5.632085295479749,
  'C6H6(GT)_R2': 0.24184178633372533,
  'C6H6(GT)_WAPE': np.float64(0.5371826529770661),
  'NOx(GT)_MAPE': 0.682037266403898,
  'NOx(GT)_MAE': 134.37906568339488,
  'NOx(GT)_MSE': 32923.81080545644,
  'NOx(GT)_RMSE': 181.44919621055487,
  'NOx(GT)_R2': 0.24831197335347188,
  'NOx(GT)_WAPE': np.float64(0.44614264288682143),
  'NO2(GT)_MAPE': 0.284132051367026,
  'NO2(GT)_MAE': 38.364741155005866,
  'NO2(GT)_MSE': 2554.4333219850464,
  'NO2(GT)_RMSE': 50.541402057966756,
  'NO2(GT)_R2': 0.12668833052399076,
  'NO2(GT)_WAPE': np.float64(0.268838938328075),
  'T_MAPE': 18996663872476.484,
  'T_MAE': 2.980624073575222,
  'T_MSE': 13.911031305850498,
  'T_RMSE': 3.729749496393893,
  'T_R2': 0.5991462013961304,
  'T_WAPE': np.float64(0.29763446024713913),
  'RH_MAPE': 0.2572511644517666,
  'RH_MAE': 9.220253066610532,
  'RH_MSE': 141.54768610327235,
  'RH_RMSE': 11.897381480950855,
  'RH_R2': 0.4804792161622957,
  'RH_WAPE': np.float64(0.18533936387059935)}}

## 2. What would be the error if we predicted the average values for all variables (Dummy Forecaster)?

In [30]:
X_train_val, y_train_val = split_X_y(train_val)
X_test, y_test = split_X_y(test)

In [31]:
train_val_targets_flat = pd.DataFrame(y_train_val.reshape(-1, len(variables)), columns=variables)
avg_values = train_val_targets_flat.mean(axis=0).to_numpy()

In [32]:
n_test = y_test.shape[0]
dummy_pred = np.tile(avg_values, (n_test, FORECAST_HORIZON, 1))

dummy_pred_flat = dummy_pred.reshape(-1, n_variables)
y_test_flat = pd.DataFrame(y_test.reshape(-1, n_variables), columns=variables)

In [33]:
dummy_error_results = get_error_results(y_test_flat, dummy_pred_flat, variables)
print(f"Error metrics for Dummy Forecaster (predicting average values): \n{dummy_error_results}")

Error metrics for Dummy Forecaster (predicting average values):
{'Avg_MAPE': 8234635315137.397, 'Avg_MAE': 39.6761911395693, 'Avg_MSE': 9050.378952062862, 'Avg_RMSE': 54.45008211461132, 'Avg_R2': -0.6663866828639414, 'Avg_WAPE': np.float64(0.46353477371226653), 'CO(GT)_MAPE': 1.4907392486029176, 'CO(GT)_MAE': 1.1496764140739417, 'CO(GT)_MSE': 2.0059470835605415, 'CO(GT)_RMSE': 1.4163146131988265, 'CO(GT)_R2': -0.044918799672288845, 'CO(GT)_WAPE': np.float64(0.6055882539246806), 'C6H6(GT)_MAPE': 2.4158267445655204, 'C6H6(GT)_MAE': 5.998942145850846, 'C6H6(GT)_MSE': 49.37824329877635, 'C6H6(GT)_RMSE': 7.026965440271949, 'C6H6(GT)_R2': -0.18020386569282976, 'C6H6(GT)_WAPE': np.float64(0.7497712562918357), 'NOx(GT)_MAPE': 0.69058204879659, 'NOx(GT)_MAE': 152.82861005522278, 'NOx(GT)_MSE': 49209.25736669915, 'NOx(GT)_RMSE': 221.8315968627985, 'NOx(GT)_R2': -0.12350328403007582, 'NOx(GT)_WAPE': np.float64(0.5073956992631622), 'NO2(GT)_MAPE': 0.38503788600654415, 'NO2(GT)_MAE': 53.84588657162112, 'NO2(GT)_MSE': 4627.602712434949, 'NO2(GT)_RMSE': 68.02648537470498, 'NO2(GT)_R2': -0.5820884482229332, 'NO2(GT)_WAPE': np.float64(0.3773222637098321), 'T_MAPE': 49407811890819.555, 'T_MAE': 10.715515800495881, 'T_MSE': 141.10016475956155, 'T_RMSE': 11.878559035487493, 'T_R2': -3.06587662581959, 'T_WAPE': np.float64(1.0700130854558751), 'RH_MAPE': 0.33398021604189093, 'RH_MAE': 13.518515850140027, 'RH_MSE': 272.92927810066453, 'RH_RMSE': 16.52057136120493, 'RH_R2': -0.0017290737459678684, 'RH_WAPE': np.float64(0.27174016917310295)}

In [34]:
df_comparison = pd.DataFrame({
    "Trained Model": pd.Series(error_results),
    "Dummy Forecaster": pd.Series(dummy_error_results)
})

df_comparison = df_comparison.round(5)
df_comparison

               Trained Model  Dummy Forecaster
Avg_MAPE        3.166111e+12      8.234635e+12
Avg_MAE         3.169117e+01      3.967619e+01
Avg_MSE         5.944486e+03      9.050379e+03
Avg_RMSE        4.241185e+01      5.445008e+01
Avg_R2          3.199100e-01     -6.663900e-01
Avg_WAPE        3.702500e-01      4.635300e-01
CO(GT)_MAPE     9.879300e-01      1.490740e+00
CO(GT)_MAE      9.043200e-01      1.149680e+00
CO(GT)_MSE      1.491600e+00      2.005950e+00
CO(GT)_RMSE     1.221310e+00      1.416310e+00
CO(GT)_R2       2.230100e-01     -4.492000e-02
CO(GT)_WAPE     4.763500e-01      6.055900e-01
C6H6(GT)_MAPE   1.271780e+00      2.415830e+00
C6H6(GT)_MAE    4.298010e+00      5.998940e+00
C6H6(GT)_MSE    3.172038e+01      4.937824e+01
C6H6(GT)_RMSE   5.632090e+00      7.026970e+00
C6H6(GT)_R2     2.418400e-01     -1.802000e-01
C6H6(GT)_WAPE   5.371800e-01      7.497700e-01
NOx(GT)_MAPE    6.820400e-01      6.905800e-01
NOx(GT)_MAE     1.343791e+02      1.528286e+02
NOx(GT)_MSE     3.292381e+04      4.920926e+04
NOx(GT)_RMSE    1.814492e+02      2.218316e+02
NOx(GT)_R2      2.483100e-01     -1.235000e-01
NOx(GT)_WAPE    4.461400e-01      5.074000e-01
NO2(GT)_MAPE    2.841300e-01      3.850400e-01
NO2(GT)_MAE     3.836474e+01      5.384589e+01
NO2(GT)_MSE     2.554433e+03      4.627603e+03
NO2(GT)_RMSE    5.054140e+01      6.802649e+01
NO2(GT)_R2      1.266900e-01     -5.820900e-01
NO2(GT)_WAPE    2.688400e-01      3.773200e-01
T_MAPE          1.899666e+13      4.940781e+13
T_MAE           2.980620e+00      1.071552e+01
T_MSE           1.391103e+01      1.411002e+02
T_RMSE          3.729750e+00      1.187856e+01
T_R2            5.991500e-01     -3.065880e+00
T_WAPE          2.976300e-01      1.070010e+00
RH_MAPE         2.572500e-01      3.339800e-01
RH_MAE          9.220250e+00      1.351852e+01
RH_MSE          1.415477e+02      2.729293e+02
RH_RMSE         1.189738e+01      1.652057e+01
RH_R2           4.804800e-01     -1.730000e-03
RH_WAPE         1.853400e-01      2.717400e-01